# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94aaf95318506e2843c0a191f75398acc5278cfd23556f37dc7a4ea623a71026b9b9decf4878bddd9449f469d78f3c283afb5ee3ba1dfaf87646b492637af352

test:
  secret_key_base: 8fb5d94d4602ee0dc72adbc3717241106e2d46ba12a588950b5614529d0bac0a531b06f59e85a31bd3ac6d21aa86e976c57dfb5bf37a4abd3b5322aa3ce632f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
